name: my_tests
on: 
  push:
    branches: [main]

jobs:   
  my_build_test:
     runs_on: ubuntu-latest
     steps:
     - uses: actions/checkout@v3
     - name: Set up Python 3.10.4
     - uses: actions/setup-python@v3
     - with: 
         python-version: 3.10.4
    - name: install Python packages
     run: 
         python -m pip install  --upgrade pip
         if [-f requirements.txt] ; then pip install -r requirements.txt; fi
    - name: Run `pytest` : penguin:
      run: | 
        pytest
    - name: Run `pylint` : thumbsup:
      run: |
        pylint my_program.py
        
     


    